### ISSUE TITLE
Optimizing CCC Control Mappings

### ISSUE THREAD

**Issue by mlysaght2017** [finos/common-cloud-controls#661]
### Description of Problem:

One of our current objectives for the controls catalog is to map CCC controls to security controls in other frameworks. At present, we attempt to maintain mappings across three distinct frameworks: NIST 800-53, CCM (Cloud Controls Matrix), and ISO 27001/27002. However, ensuring accurate mappings even to a single framework is a challenge, with ongoing discussions around improving the accuracy of our current mappings to NIST 800-53.

While there is consensus that mapping CCC controls to NIST 800-53 provides some value, there is an emerging view that maintaining mappings to CCM and ISO 27001/27002 does not justify the associated maintenance overhead. Given this, we need to evaluate whether to continue mapping controls across all three frameworks or refine our approach to reduce complexity and improve accuracy.

### Potential Solutions:

To address this issue, the following options are being considered:

1. **Remove all framework mappings:** Discontinue mapping CCC controls to any external framework and remove all existing mappings. Any future mapping efforts would be conducted separately from the controls catalog.
2. **Focus solely on NIST 800-53:** Retain mappings only to NIST 800-53 and remove all existing mappings to CCM and ISO 27001/27002, reducing maintenance effort while still maintaining a connection to a widely adopted framework.
3. **Continue mapping to all three frameworks:** Maintain the current approach of mapping CCC controls to NIST 800-53, CCM, and ISO 27001/27002, accepting the associated complexity and overhead.

A decision on the preferred approach is required to ensure that our controls catalog remains both effective and maintainable.

**Comment by mlysaght2017** [comment]
@eddie-knight @damienjburks @robmoffat - please choose one of the 3 options above or add in any others worth considering. Please tag anyone else you think should be part of the decision.

**Comment by SecurityCRob** [comment]
Hey there, long-time observer, first-time commentator here.....

Having done these things for <redacted timeframe> I would advise you that while it is hard and tedious, there is immense value for the implementer/consumer of your mappings.  Being able to show a regulator or auditor that the "why" behind your program's actions/controls is SO valuable.  It moves the conversation from "why did you make all of this up?" to "we're following industry-best practices that are internationally recognized".  It also helps practitioners focus their efforts and see where controls assist them across multiple regulations to reduce complexity and rework for themselves and their stakeholders.

#3 is the most "expensive" for this group, but adds the maximum amount of value to your downstream.  We're working up something similar within the OpenSSF, but focused not on enterprise operators, but upstream developers/projects and their downstream consumers.  I am very well aware of the level of effort and review this requires to stand up and maintain, and for us that investment in time is worth it for our downstream.

I would avoid #1 at all costs.  If #3 is not doable by the team here, #2 could be an acceptable MVP to still over value to your downstream stakeholders.

If there is interest, I'd be glad to collaborate with you all to review/revise your mappings.

**Comment by jdawJoe** [comment]
I would agree with the above.  The best and most usable value is the NIST mapping, as that is more universally used and you wouldn't want to create too much to try and upkeep. Mapping between 2 frameworks is a great effort.  Adding more than that can be tough.  Def go with #2 IMO.  Thanks all.

**Comment by eddie-knight** [comment]
I've been chewing on a revised structure for writing the mappings. This would allow the control author to choose as many or as few mappings as they'd like to provide, and — more importantly — increase precision around versioning.

<details><summary>Click for details</summary>

## Current mapping approach:

```yaml
    nist_csf: PR.DS-2
    mitre_attack: T1573
    control_mappings:
      CCM: 
        - IVS-09
        - DSI-03
      ISO_27001: 
        - 2013 A.13.1.1
      NIST_800_53: 
        - SC-8
        - SC-13
```

## Proposed mapping approach:

```yaml
    mitre_attack: T1573
    control_mappings:
      - framework: NIST CSF
        version: 1.1
        controls:
          - PR.DS-2
      - framework: CCM
        version: 4
        controls:
          - IVS-09
          - DSI-03
      - framework: ISO-27001
        version: 2013
        controls:
          - A.13.1.1
      - framework: NIST-800-53
        version: 5
        controls:
          - SC-8
          - SC-13
```
</details>
